### ISSUE TITLE
How about adding new types?

### ISSUE THREAD

**Issue by hissy** [concretecms/doctrine-xml#9]
How about adding new types in the xsd file?

Available since version 2.6:

* date_immutable
* datetime_immutable
* datetimetz_immutable
* time_immutable
* json

Available since version 2.5:

* simple_array
* json

Also, these types will be deprecated from Doctrine DBAL 3.4.0. We may need to consider to remove them from version 10.

* array
* object

**Comment by mlocati** [comment]
I've checked all the DBAL data types from v2.4 to v4.0rc1:

- `ascii_string` has been introduced in 2.11
- `guid` has been introduced in 2.5
- `binary` has been introduced in 2.5
- `blob` has been introduced in 2.5
- `date_immutable` has been introduced in 2.6
- `datetime_immutable` has been introduced in 2.6
- `datetimetz` has been introduced in 2.5
- `datetimetz_immutable` has been introduced in 2.6
- `time_immutable` has been introduced in 2.6
- `dateinterval` has been introduced in 2.6
- `array` has been deprecated since 3.4
- `simple_array` has been introduced in 2.5
- `json` has been introduced in 2.6
- `json_array` has been introduced in 2.5, deprecated since 2.6, and removed from 3.3
- `object` has been deprecated since 3.4

I'm going to submit a PR with the new types and the above details.
